name: stork_hub
description: An application that helps you manage your Stork's apps
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  dart_stork_admin_client:
    git:
      url: https://github.com/stork-delivery/dart_stork_admin_client.git
      ref: main
  encrypt: ^5.0.3
  equatable: ^2.0.5
  file_selector: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.1
  pointycastle: ^3.7.3

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
